name: flutter_application_1
description: "Application scolaire Parent & Étudiant"
publish_to: 'none' # Ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Dépendances optionnelles que tu peux activer si besoin
  # provider: ^6.0.5
  # go_router: ^6.5.0
  # http: ^0.13.5
  # file_picker: ^5.2.3
  # flutter_pdfview: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Fonts
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

  # Assets (images, icons, etc.)
  assets:
    - assets/
    - assets/payment.png
    - assets/profile2.png
    - assets/folder.png
    - assets/doc.png
    - assets/laz.jpg
    # ajoute d'autres images si nécessaire


